name: Publish Version Check Results

on:
  workflow_run:
    workflows: [ 'Pull-Request Checks' ]
    types: [ completed ]

permissions: {}

jobs:
  publish-version-check-results:
    if: github.event.workflow_run.conclusion != 'skipped'
    uses: ./.github/workflows/publishVersionCheckResults.yml
    with:
      botGithubId: eclipse-jdt-bot
    secrets:
      githubBotPAT: ${{ secrets.JDT_BOT_PAT }}
